default:
  user: !expr keyring::key_list("cmpdb")[1,2]
  password: !expr keyring::key_get("cmpdb", keyring::key_list("cmpdb")[1, 2])
  host: "HOST IP"
  port: "HOST PORT AS AN INTEGER"
  dbname: "NAME OF DB TO CONNECT TO"

admin:
  user: !expr keyring::key_list("cmpdb-admin")[1,2]
  password: !expr keyring::key_get("cmpdb-admin", keyring::key_list("cmpdb-admin")[1, 2])
  host: "HOST IP"
  port: "HOST PORT AS AN INTEGER"
  dbname: "NAME OF DB TO CONNECT TO"

